spring:
  profiles:
    active:
      - dev
  servlet:
    multipart.max-file-size: 100MB
    max-request-size: 100MB
springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui
jwt:
  private:
    key: classpath:rsa.private.key
  public:
    key: classpath:rsa.public.key
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: "cool-chat"
      port: 27017
      host: localhost
      auto-index-creation: true
  minio:
    container:
      port: "9000"
    buckets:
      app: app
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: "cool-chat"
      port: 27017
      host: localhost
      auto-index-creation: true
  minio:
    container:
      port: "9000"
    buckets:
      app: app
---
spring:
  config:
    activate:
      on-profile: test-db
  data:
    mongodb:
      port: ${mongodb.container.port}
---
spring:
  config:
    activate:
      on-profile: test-minio
  minio:
    container:
      port: ${minio.container.port}
    buckets:
      app: app