spring:
  profiles:
    active:
      - dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/cool-chat
  servlet:
    multipart.max-file-size: 100MB
    max-request-size: 100MB
  mongodb:
    embedded:
      version: 5.0.5
springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui
jwt:
  private:
    key: classpath:rsa.private.key
  public:
    key: classpath:rsa.public.key
---
spring:
  config:
    activate:
      on-profile: prod
cool-messenger:
  uploads-folder: uploads
---
spring:
  config:
    activate:
      on-profile: dev
cool-messenger:
  uploads-folder: uploads-test
---
spring:
  config:
    activate:
      on-profile: test
cool-messenger:
  uploads-folder: uploads-test