spring:
  profiles:
    active:
      - dev
  data:
    mongodb:
      database: "cool-chat"
      port: 27017
      host: localhost
      auto-index-creation: true
  servlet:
    multipart.max-file-size: 100MB
    max-request-size: 100MB
springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui
jwt:
  private:
    key: classpath:rsa.private.key
  public:
    key: classpath:rsa.public.key
---
spring:
  config:
    activate:
      on-profile: prod
cool-messenger:
  uploads-folder: uploads
---
spring:
  config:
    activate:
      on-profile: dev
cool-messenger:
  uploads-folder: uploads-test
---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      port: ${mongodb.container.port}
cool-messenger:
  uploads-folder: uploads-test