spring:
  profiles:
    active:
      - dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/cool-chat
springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui
jwt:
  private:
    key: classpath:rsa.private.key
  public:
    key: classpath:rsa.public.key
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://localhost:27018/cool-chat
