spring:
  profiles:
    active:
      - dev
springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui
jwt:
  private:
    key: classpath:rsa.private.key
  public:
    key: classpath:rsa.public.key
---
spring:
  config:
    activate:
      on-profile: dev
